### ISSUE TITLE
data scrapping does not work anymore!!! 

### ISSUE THREAD

**Issue by blueswallow99** [PushkaraSharma/Automatic_Movie_Review_NLP#1]
hey there I was using your scrapping code to extract movie reviews, it use to work but now suddenly it has a error 
**for a in c.find_all('a',href =True):
AttributeError: 'NoneType' object has no attribute 'find_all'**
I have checked the tags and everything they are all correct I have no idea why it stopped working, do you mind checking it out?

**Comment by PushkaraSharma** [comment]
hey there, first of thanks for using this project and reporting the issue.  Please give me some time to set It on local and start debugging this issue. Will try to come up with a solution as soon as possible.

**Comment by PushkaraSharma** [comment]
This issue is resolved. Hence,  closing this issue
